services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: invoicing_frontend_prod
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - invoicing_network_prod
    restart: unless-stopped
    depends_on:
      - backend

  frontend_nginx:
    image: nginx:alpine
    container_name: invoicing_frontend_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html:ro
    networks:
      - invoicing_network_prod
    depends_on:
      - backend_nginx
      - frontend
    restart: unless-stopped

volumes:
  frontend_dist:
