services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoicing_frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - invoicing_network
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL}

  frontend_nginx:
    image: nginx:alpine
    container_name: invoicing_frontend_nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - invoicing_network
    depends_on:
      - backend_nginx
      - frontend
